baseURL = 'https://welmnaiisposa368.github.io/cheap-account-shop/'
languageCode = 'en-us'
title = 'My Cheap Account Shop'
theme = 'hugo-cards'

[params]
  assetsPath = '/cheap-account-shop/'

[outputs]
  home = ['HTML', 'CSS', 'JS']
